config/routes.rb
Rails.application.routes.draw do
  devise_for :customer_users, controllers: {
    sessions: 'customer_users/sessions',
    passwords: 'customer_users/passwords',
    registrations: 'customer_users/registrations'
  }
  devise_scope :customer_user do
    post 'customer_users/guest_sign_in', to: 'customer_users/sessions#guest_sign_in'
  end

  devise_for :owner_users, controllers: {
    sessions: 'owner_users/sessions',
    passwords: 'owner_users/passwords',
    registrations: 'owner_users/registrations'
  }
  devise_scope :owner_user do
    post 'owner_users/guest_sign_in', to: 'owner_users/sessions#guest_sign_in'
  end

  root to: 'stores#index'

  resources :stores, except: [:index] do
    resources :reviews, only: [:index, :create]
    resources :bookmarks, only: [:create, :destroy]
    collection do
      get 'keyword_search'
    end
  end
  resources :tags do
    get 'tag_search', to: 'stores#tag_search'
  end
  resources :customer_users, only: [:index, :show]
  
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :customer_user
  belongs_to :store

  validates_uniqueness_of :store_id, scope: :customer_user_id
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_customer_user!
  before_action :set_store

  def create
    Bookmark.create(customer_user_id: current_customer_user.id, store_id: @store.id)
  end

  def destroy
    bookmark = Bookmark.find_by(customer_user_id: current_customer_user.id, store_id: @store.id)
    bookmark.destroy
  end

  private

  def set_store
    @store = Store.find(params[:store_id])
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_bkm.html.erb
<%= link_to store_bookmarks_path(@store), method: :post, remote: true do %>
  <i class="far fa-bookmark icon"></i>
<% end %>

app/views/bookmarks/_bookmark.html.erb
<% if !Bookmark.exists?(customer_user_id: current_customer_user.id, store_id: store.id) %>
  <%= render 'bookmarks/bkm', store: store %>
<% else %>
  <%= render 'bookmarks/unbkm', store: store %>
<% end %>

app/views/bookmarks/_unbkm.html.erb
<%= link_to store_bookmark_path(@store), method: :delete, remote: true do %>
  <i class="fas fa-bookmark icon"></i>
<% end %>

app/views/bookmarks/create.js.erb
console.log("create")
$('#bookmark-icon').html("<%= j(render partial: 'bookmarks/unbkm') %>");

app/views/bookmarks/destroy.js.erb
console.log("destroy")
$('#bookmark-icon').html("<%= j(render partial: 'bookmarks/bkm') %>");