config/routes.rb
Rails.application.routes.draw do
  devise_for :customer_users, controllers: {
    sessions: 'customer_users/sessions',
    passwords: 'customer_users/passwords',
    registrations: 'customer_users/registrations'
  }
  devise_scope :customer_user do
    post 'customer_users/guest_sign_in', to: 'customer_users/sessions#guest_sign_in'
  end

  devise_for :owner_users, controllers: {
    sessions: 'owner_users/sessions',
    passwords: 'owner_users/passwords',
    registrations: 'owner_users/registrations'
  }
  devise_scope :owner_user do
    post 'owner_users/guest_sign_in', to: 'owner_users/sessions#guest_sign_in'
  end

  root to: 'stores#index'

  resources :stores, except: [:index] do
    resources :reviews, only: [:index, :create]
    resources :bookmarks, only: [:create, :destroy]
    collection do
      get 'keyword_search'
    end
  end
  resources :tags do
    get 'tag_search', to: 'stores#tag_search'
  end
  resources :customer_users, only: [:index, :show]
  
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :owner_user
  has_one_attached :image
  has_many :comments
  has_many :reviews, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :store_tag_relations, dependent: :destroy
  has_many :tags, through: :store_tag_relations

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def avg_score
    if reviews.empty?
      0.0
    else
      reviews.average(:score).round(1).to_f
    end
  end

  def review_score_percentage
    if reviews.empty?
      0.0
    else
      reviews.average(:score).round(1).to_f * 100 / 5
    end
  end

  def self.keyword_search(search)
    if search != ''
      Store.where('name LIKE(?) OR station LIKE(?) OR address LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%")
    else
      Store.all
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_owner_user!, only: [:new, :create, :edit]
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Tag.all
    @stores = Store.all.order(created_at: :desc).page(params[:page]).per(6)
  end

  def new
    @store_tag = StoresTag.new
  end

  def create
    @store_tag = StoresTag.new(store_params)
    tag_list = params[:store][:word].split(',')
    if @store_tag.valid?
      @store_tag.save(tag_list)
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    redirect_to root_path unless owner_user_signed_in? && current_owner_user == @store.owner_user
    @store_tag = StoresTag.new(store: @store)
  end

  def update
    redirect_to root_path unless owner_user_signed_in? && current_owner_user == @store.owner_user
    @store_tag = StoresTag.new(store_params, store: @store)
    tag_list = params[:store][:word].split(',')
    if @store_tag.valid?
      @store_tag.save(tag_list)
      redirect_to store_path(@store)
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path unless owner_user_signed_in? && current_owner_user == @store.owner_user
    @store.destroy
    redirect_to root_path
  end

  # タグ検索
  def tag_search
    @tags = Tag.all
    @tag = Tag.find(params[:tag_id])
    @stores = @tag.stores.all.page(params[:page]).per(6)
  end

  # キーワード検索
  def keyword_search
    @tags = Tag.all
    @stores = Store.keyword_search(params[:keyword]).order(created_at: :desc).page(params[:page]).per(6)
    @keyword = params[:keyword]
  end

  private

  def store_params
    params.require(:store).permit(:name, :image, :address, :station, :price, :store_time,
                                  :link, :word).merge(owner_user_id: current_owner_user.id)
  end

  def set_store
    @store = Store.find(params[:id])
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/edit.html.erb
<%= render "shared/header"  %>

<%= form_with model: @store, url: store_path, class: "registration-main", local: true do |f| %>

<div class="form-wrap">
  <div class="form-header">
    <h4 class="form-header-text">店舗情報を編集する</h2>
  </div>

<%= render 'shared/error_messages', model: f.object %>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">お店の写真をアップロード</label>
    </div>
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">店舗名</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :name, class: "input-default" %>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">住所</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :address, class: "input-default" %>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">最寄駅</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :station, placeholder: "例）渋谷駅", class: "input-default" %>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">料金（1Hあたり）</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :price, class: "input-default" %>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">営業時間</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :store_time, placeholder: "例) 平日：10:00-20:00  土日祝：10:00-2200", class: "input-default" %>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">店舗のホームページURL</label>
    </div>
    <%= f.url_field :link, class: "input-default" %>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">タグ</label>
    </div>
    <% word_str = @store.tags.pluck(:word).join(',') %>
    <%= f.text_field :word, value: word_str, class: "input-default"   %>
  </div>

  <div class="register-btn">
    <%= f.submit "登録する", class: "register-btn-item" %>
  </div>
</div>

<% end %>

<%= render "shared/footer"  %>

app/views/stores/index.html.erb
<%= render "shared/header" %>

<div class="main">
  
  <%= render "shared/top_search_form" %>

  <div class="top-page-main">
    <div class="container">
      <div class="stores-title pt-4 ">
        <h5 class="text-center"><span class="title">仮眠処 一覧</span></h5>
      </div>
      
      <%= render partial: "shared/store_list", locals: { stores: @stores } %>

    <div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/stores/keyword_search.html.erb
<%= render "shared/header" %>

<div class="main">
  
  <%= render "shared/top_search_form" %>

  <div class="top-page-main">
    <div class="container">
      <div class="stores-title pt-4 ">
        <h5 class="text-center"><span class="title">「<%= @keyword %>」の検索結果</span></h5>
      </div>
      
      <%= render partial: "shared/store_list", locals: { stores: @stores } %>

    <div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/stores/new.html.erb
<%= render "shared/header"  %>

<%= form_with model: @store_tag, url: stores_path, class: "registration-main", local: true do |f| %>

<div class="form-wrap">
  <div class="form-header">
    <h4 class="form-header-text">店舗を登録する</h2>
  </div>

  <%= render 'shared/error_messages', model: f.object %>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">お店の写真をアップロード</label>
    </div>
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">店舗名</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :name, class: "input-default" %>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">住所</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :address, class: "input-default" %>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">最寄駅</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :station, placeholder: "例）渋谷駅", class: "input-default" %>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">料金（1Hあたり）</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_field :price, class: "input-default" %>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">営業時間</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :store_time, placeholder: "例) 平日：10:00-20:00  土日祝：10:00-2200", class: "input-default" %>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">店舗のホームページURL</label>
    </div>
    <%= f.url_field :link, placeholder: "https://example.com", class: "input-default" %>
  </div>

  <div class="form-group">
    <div class="form-text-wrap">
      <label class="form-text">タグ</label>
    </div>
    <%= f.text_field :word, placeholder: "タグ1, タグ2", class: "input-default" %>
  </div>
  <div id="search-result">
  </div>

  <div class="register-btn">
    <%= f.submit "登録する", class: "register-btn-item" %>
  </div>
</div>

<% end %>

<%= render "shared/footer"  %>

app/views/stores/show.html.erb
<%= render 'shared/header' %>

<div class="store-show">
  <div class="store-show-top">
      <h3 class="store-show-name"><%= @store.name %></h3>
    <% if customer_user_signed_in? %>
      <div id="bookmark-icon" class="bookmark-icon">
        <%= render 'bookmarks/bookmark', store: @store %>
      </div>
    <% end %>
  </div>

  <div class="store-show-content">
    <div class="store-show-card">
      <div class="store-show-img-content">
        <%= image_tag @store.image.variant(resize: '500x500'), class:"store-show-img" %>
      </div>
        <ul class="store-tags list-inline">
          <% @store.tags.each do |tag| %>
            <li class="tag list-inline-item"><%= link_to tag.word, tag_tag_search_path(tag), class: "tag-word" %></li>
          <% end %>
        </ul>
      <div class="show-review">
        <div class="star-rating">
          <div class="star-rating-front" style="width: <%= @store.review_score_percentage %>%">★★★★★</div>
          <div class="star-rating-back">★★★★★</div>
        </div>
        <div class="review-link">
          <%= link_to store_reviews_path(@store) do %>
            <%= @store.avg_score %>点（<%= @store.reviews.count %>件）
          <% end %>
        </div>
      </div>
      
      <div class="store-infos">
        <h5 class="store-infos-text">店舗情報</h5>

        <div class="store-info">
          <div class="store-info-title">
            所在地
          </div>
          <div class="store-info-content">
            <%= @store.address %>
          </div>
        </div>
        <div class="store-info">
          <div class="store-info-title">
            最寄駅
          </div>
          <div class="store-info-content">
            <%= @store.station %>
          </div>
        </div>
        <div class="store-info">
          <div class="store-info-title">
            料金（1Hあたり）
          </div>
          <div class="store-info-content">
            ¥ <%= @store.price %>
          </div>
        </div>
        <div class="store-info">
          <div class="store-info-title">
            営業時間
          </div>
          <div class="store-info-content">
            <%= @store.store_time %>
          </div>
        </div>
        <div class="store-info">
          <div class="store-info-title">
            ホームページ
          </div>
          <div class="store-info-content">
            <%= link_to "#{@store.link}", @store.link %>
          </div>
        </div>
      </div>

      <% if current_owner_user == @store.owner_user %>
        <ul class="owner-menu list-inline">
          <li class="edit-btn list-inline-item"><%= link_to "編集", edit_store_path(@store), class: "edit-link" %></li>
          <li class="delete-btn list-inline-item "><%= link_to "削除", store_path(@store), method: :delete, class: "delete-link" %></li>
        </ul>
      <% end %>
    </div>
  </div>

  <div id="map" class="map">
  </div>
</div>

<script>
  function initMap() {
    var location ={lat: <%= @store.latitude %>, lng: <%= @store.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15, 
      center: location,
      mapTypeControl: false,
      streetViewControl: false
      });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '住所：<%= @store.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

    var marker = new google.maps.Marker({
      position: location,
      map: map,
      title: contentString
    });

    marker.addListener('click', function() {
      infowindow.open(map, marker);
    });
  }
</script>

<script async defer
  src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['MAP_ACCESS_KEY'] %>&callback=initMap">
</script>

<%= render 'shared/footer' %>

app/views/stores/tag_search.html.erb
<%= render "shared/header" %>

<div class="main">

  <%= render "shared/top_search_form" %>

  <div class="top-page-main">
    <div class="container">
      <div class="stores-title pt-4 ">
        <h5 class="text-center"><span class="title">「<%= @tag.word %>」の検索結果</span></h5>
      </div>
      
      <%= render partial: "shared/store_list", locals: { stores: @stores } %>

    <div>
  </div>
</div>

<%= render "shared/footer" %>