config/routes.rb
Rails.application.routes.draw do
  devise_for :customer_users, controllers: {
    sessions: 'customer_users/sessions',
    passwords: 'customer_users/passwords',
    registrations: 'customer_users/registrations'
  }
  devise_scope :customer_user do
    post 'customer_users/guest_sign_in', to: 'customer_users/sessions#guest_sign_in'
  end

  devise_for :owner_users, controllers: {
    sessions: 'owner_users/sessions',
    passwords: 'owner_users/passwords',
    registrations: 'owner_users/registrations'
  }
  devise_scope :owner_user do
    post 'owner_users/guest_sign_in', to: 'owner_users/sessions#guest_sign_in'
  end

  root to: 'stores#index'

  resources :stores, except: [:index] do
    resources :reviews, only: [:index, :create]
    resources :bookmarks, only: [:create, :destroy]
    collection do
      get 'keyword_search'
    end
  end
  resources :tags do
    get 'tag_search', to: 'stores#tag_search'
  end
  resources :customer_users, only: [:index, :show]
  
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer text-center">
  Copyright Kamindokoro
</footer>

app/views/shared/_header.html.erb
<header class="d-flex justify-content-between align-items-center py-4">

  <%= link_to root_path, class: "top-title" do %>
    <img src="/images/logo.png" width="130px">
  <% end %>

  <nav class="nav justify-content-end">
    <% if customer_user_signed_in? %>
    <div class="dropdown">
      <button class="btn dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">メニュー
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
        <%= link_to "マイページ", customer_user_path(current_customer_user), class:"dropdown-item" %>
        <%= link_to "ログアウト", destroy_customer_user_session_path, method: :delete, class:"dropdown-item" %>
      </div>
    </div>
    <% elsif owner_user_signed_in? %>
      <div class="dropdown">
        <button class="btn dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">メニュー
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
          <%= link_to "お店を登録", new_store_path, class:"dropdown-item" %>
          <%= link_to "ログアウト", destroy_owner_user_session_path, method: :delete, class:"dropdown-item" %>
        </div>
      </div>
    <% else %>
      <div class="dropdown">
        <button class="btn dropdown-toggle" type="button" id="dropdownMenu3" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">一般の方
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenu3">
          <%= link_to "新規登録", new_customer_user_registration_path, class:"dropdown-item" %>
          <%= link_to "ログイン", new_customer_user_session_path, class:"dropdown-item" %>
          <%= link_to 'ゲストログイン', customer_users_guest_sign_in_path, method: :post, class:"dropdown-item" %>
        </div>
      </div>
      <div class="dropdown">
        <button class="btn dropdown-toggle" type="button" id="dropdownMenu4" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">オーナーの方
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenu4">
            <%= link_to "オーナー登録", new_owner_user_registration_path, class:"dropdown-item" %>
            <%= link_to "ログイン", new_owner_user_session_path, class:"dropdown-item" %>
            <%= link_to 'ゲストログイン', owner_users_guest_sign_in_path, method: :post, class:"dropdown-item" %>
        </div>
      </div>
    <% end %>
  </nav>
</header>

app/views/shared/_store_list.html.erb
<div class="stores my-5 row">
  <% @stores.each do |store| %>
    <div class="store col-xl-4 col-md-6 col-12 ">
      <div class="store-card">
        <div class="store-img">
          <%= link_to store_path(store) do %>
            <%= image_tag store.image.variant(resize: '340x220'), class:"img-responsive" %>
          <% end %>
        </div>
        <div class="store-content p-3">
          <div class="store-name">
            <%= store.name %>
          </div>
          <ul class="store-tags list-inline">
          <% store.tags.each do |tag| %>
            <li class="tag list-inline-item"><%= link_to tag.word, tag_tag_search_path(tag), class: "tag-word" %></li>
          <% end %>
          </ul>
          <div class="star-rating">
            <div class="star-rating-front" style="width: <%= store.review_score_percentage %>%">★★★★★</div>
            <div class="star-rating-back">★★★★★</div>
          </div>
        </div>
      </div>
    </div>
  <%end%>
</div>

<%= paginate @stores %>

app/views/shared/_top_search_form.html.erb
<div class="home-header text-center">
  <div class="home-title col-12">
    <h1>さあ、寝よう　　　　　　　　　　</h1>
  </div>
  <div class="search-form">
    <%= form_with(url: keyword_search_stores_path, local: true, method: :get) do |f| %>
      <%= f.text_field :keyword, placeholder: "店舗名・地名・駅名", class:" search-form col-6" %>
      <%= f.submit "検索",  class:"search-btn" %>
    <% end %>
  </div>
</div>

<div class="tag-index text-center">
  <div class="tag-index-title pt-4 ">
    <h5><span class="title">こだわりから探す</span></h5>
  </div>
  <div class="tag-index-list"> 
  <% @tags.each do |tag| %>
    <div class="top-tag ">
      <%= link_to tag.word, tag_tag_search_path(tag), class: "tag-word" %>
    </div>
  <% end %>
  </div>
</div>